import 'package:flutter/material.dart';

/// Approved three-person mark. Generated by scripts/export-brand.py.
class VriendTimeMarkPainter extends CustomPainter {
  const VriendTimeMarkPainter(
      {this.small = false,
      this.top = 0,
      this.left = 0,
      this.right = 0,
      this.centerOpacity = 1});
  final bool small;
  final double top, left, right, centerOpacity;
  @override
  void paint(Canvas canvas, Size size) {
    canvas.save();
    canvas.scale(size.width / 774, size.height / 774);
    canvas.translate(-240, -135);
    canvas.save();
    canvas.translate(0, -top);
    canvas.drawCircle(
        const Offset(627, 261), 69, Paint()..color = const Color(0xFFF56853));
    canvas.drawPath(
        Path()
          ..moveTo(408, 492)
          ..cubicTo(425, 394, 457, 340, 532, 314)
          ..cubicTo(546, 309, 555, 311, 563, 320)
          ..cubicTo(598, 357, 655, 357, 690, 320)
          ..cubicTo(698, 311, 707, 309, 721, 314)
          ..cubicTo(796, 340, 829, 394, 846, 492)
          ..cubicTo(809, 417, 714, 381, 627, 381)
          ..cubicTo(540, 381, 445, 417, 408, 492)
          ..close(),
        Paint()..color = const Color(0xFFF56853));
    canvas.restore();
    canvas.save();
    canvas.translate(-left, 0);
    canvas.drawCircle(
        const Offset(351, 403), 64, Paint()..color = const Color(0xFF145247));
    canvas.drawPath(
        Path()
          ..moveTo(302, 488)
          ..cubicTo(308, 463, 323, 473, 340, 485)
          ..cubicTo(386, 516, 434, 524, 480, 544)
          ..cubicTo(533, 568, 553, 642, 614, 795)
          ..cubicTo(620, 811, 601, 812, 580, 806)
          ..cubicTo(419, 771, 297, 623, 300, 510)
          ..cubicTo(300, 501, 301, 494, 302, 488)
          ..close(),
        Paint()..color = const Color(0xFF145247));
    canvas.restore();
    canvas.save();
    canvas.translate(right, 0);
    canvas.drawCircle(
        const Offset(903, 403), 64, Paint()..color = const Color(0xFF145247));
    canvas.drawPath(
        Path()
          ..moveTo(952, 488)
          ..cubicTo(946, 463, 931, 473, 914, 485)
          ..cubicTo(868, 516, 820, 524, 774, 544)
          ..cubicTo(721, 568, 701, 642, 640, 795)
          ..cubicTo(634, 811, 653, 812, 674, 806)
          ..cubicTo(835, 771, 957, 623, 954, 510)
          ..cubicTo(954, 501, 953, 494, 952, 488)
          ..close(),
        Paint()..color = const Color(0xFF145247));
    canvas.restore();
    if (!small) {
      canvas.drawPath(
          Path()
            ..moveTo(444, 478)
            ..cubicTo(539, 391, 714, 391, 809, 478)
            ..cubicTo(720, 497, 669, 571, 627, 688)
            ..cubicTo(585, 571, 533, 497, 444, 478)
            ..close(),
          Paint()
            ..color = const Color(0xFFF7EBD3).withValues(alpha: centerOpacity));
    }
    canvas.restore();
  }

  @override
  bool shouldRepaint(VriendTimeMarkPainter oldDelegate) =>
      oldDelegate.small != small ||
      oldDelegate.top != top ||
      oldDelegate.left != left ||
      oldDelegate.right != right ||
      oldDelegate.centerOpacity != centerOpacity;
}
